locale                   : "en-US"
title                    : "js Final"
title_separator          : "-"
subtitle                 : js
name                     : "yoots50"
description              : "js Final"
url                      : "https://yoots50.github.io"
baseurl                  : ""
